microsoft/Dynamics-365-Fraud-Protection-Samples

Contoso.FraudProtection.sln, src/ApplicationCore/ApplicationCore.csproj, src/Infrastructure/Infrastructure.csproj, src/README.md, src/Web/Areas/Admin/Views/Manage/Edit.cshtml, src/Web/Views/Account/Register.cshtml, src/Web/Views/Account/Signin.cshtml, src/Web/Views/Manage/ChangePassword.cshtml, src/Web/Views/Manage/SetPassword.cshtml, src/Web/Web.csproj
- Upgrade to .NET Core 2.2
- Add docs and readmes to .NET solution for better visibility from within Visual Studio.
- Make button styling consistent.
=> Upgrade to .NET Core 2.2

docs/Configure the sample site.md, src/Infrastructure/Services/TokenProviderService.cs, src/Web/appsettings.json
Further clarification has been added to this documentation page.  Please let me know if you think it can be improved further.
=> Documentation - Update the configure the sample site doc.

Contoso.FraudProtection.sln, docs/Authenticate and call Fraud Protection.md, docs/Configure the sample site.md, src/ApplicationCore/Interfaces/ITokenProvider.cs, src/Infrastructure/Identity/AppIdentityDbContextSeed.cs, src/Infrastructure/Services/FraudProtectionService.cs, src/Infrastructure/Services/FraudProtectionSettings.cs, src/Infrastructure/Services/TokenProviderService.cs, src/Web/Program.cs, src/Web/appsettings.json
We need to allow the token resource URL and the API base URL to be different.  This PR paves the way for that.
=> Add explicit resource name/id to appsettings for acquiring a token against.

src/Web/Views/Shared/_Layout.cshtml
This update was missed in the previous PR #38
=> Update Device Fingerprinting variable name when reading data center value

.github/workflows/dotnetcore.yml, src/Web/Web.csproj
This PR adds a Github actions file that will auto build the .NET Core solution on PRs that target master.  You can see it on this PR.
=> Build .NET Core app on pull requests

src/ApplicationCore/Entities/FraudProtectionApiModels/AccountProtection/Address.cs, src/ApplicationCore/Entities/FraudProtectionApiModels/AccountProtection/BaseFraudProtectionEvent.cs, src/ApplicationCore/Entities/FraudProtectionApiModels/AccountProtection/CustomerEmail.cs, src/ApplicationCore/Entities/FraudProtectionApiModels/AccountProtection/CustomerPhone.cs, src/ApplicationCore/Entities/FraudProtectionApiModels/AccountProtection/DeviceContext.cs, src/ApplicationCore/Entities/FraudProtectionApiModels/AccountProtection/EventMetadata.cs, src/ApplicationCore/Entities/FraudProtectionApiModels/AccountProtection/PaymentInstrument.cs, src/ApplicationCore/Entities/FraudProtectionApiModels/AccountProtection/PaymentInstrumentCard.cs, src/ApplicationCore/Entities/FraudProtectionApiModels/AccountProtection/PaymentInstrumentPaypal.cs, src/ApplicationCore/Entities/FraudProtectionApiModels/AccountProtection/Responses/Response.cs, src/ApplicationCore/Entities/FraudProtectionApiModels/AccountProtection/Responses/ResponseError.cs, src/ApplicationCore/Entities/FraudProtectionApiModels/AccountProtection/Responses/ResponseSuccess.cs, src/ApplicationCore/Entities/FraudProtectionApiModels/AccountProtection/Responses/ResultDetail.cs, src/ApplicationCore/Entities/FraudProtectionApiModels/AccountProtection/Responses/Score.cs, src/ApplicationCore/Entities/FraudProtectionApiModels/AccountProtection/SSOAuthenticationProvider.cs, src/ApplicationCore/Entities/FraudProtectionApiModels/AccountProtection/SignIn.cs, src/ApplicationCore/Entities/FraudProtectionApiModels/AccountProtection/Signup.cs, src/ApplicationCore/Entities/FraudProtectionApiModels/AccountProtection/User.cs, src/ApplicationCore/Interfaces/IFraudPreventionService.cs, src/Infrastructure/Services/FraudProtectionService.cs, src/Infrastructure/Services/FraudProtectionSettings.cs, src/Web/Controllers/AccountController.cs, src/Web/Views/Account/Register.cshtml, src/Web/Views/Account/Signin.cshtml, src/Web/appsettings.json
Add implementation for calling new Account Creation/Account Login APIs
Add new buttons for using the new APIs when registering or logging in
=> Add new Account Protection APIs

src/ApplicationCore/Entities/FraudProtectionApiModels/AccountProtection/Responses/ResultDetail.cs, src/Infrastructure/Services/FraudProtectionService.cs, src/Infrastructure/Services/FraudProtectionSettings.cs, src/Web/appsettings.json
Change RuleSetId to Rule and use regular instance ID instead of AccountProtectionTenantId
=> Contract changes for account protection APIs

src/Web/Controllers/AccountController.cs
Send IPv4 address when calling Account Protection APIs
=> Send IPv4 address when calling Account Protection APIs

src/ApplicationCore/Entities/FraudProtectionApiModels/AccountProtection/Responses/ResultDetail.cs
Change SupportingMessages to SupportMessages
=> Change SupportingMessages to SupportMessages

Contoso.FraudProtection.sln, docs/Account sign in (Account Protection) - Approved and rejected sign in flows.md, docs/Account sign up (Account Protection) - Approved and rejected sign up flows.md, docs/Account sign up (Purchase Protection) - Approved and rejected sign up flows.md, docs/Configure the sample site.md, docs/README.md, src/Web/Controllers/AccountController.cs, src/Web/appsettings.json
- Add new pages for AP SignIn/SignUp events
- Update configuration instructions for integrating with AP APIs
=> Update documentation for Account Protection APIs

docs/Account sign in (Account Protection) - Approved and rejected sign in flows.md, docs/Account sign up (Account Protection) - Approved and rejected sign up flows.md, src/ApplicationCore/Entities/FraudProtectionApiModels/AccountProtection/Address.cs, src/ApplicationCore/Entities/FraudProtectionApiModels/AccountProtection/User.cs, src/Web/Controllers/AccountController.cs
The property has been renamed.
=> [Account Protection] Rename Country to CountryRegion

src/Web/Views/Manage/Index.cshtml, src/Web/Views/Manage/ManagePaymentInstrument.cshtml
Just fixing for Account updates/Account payment updates.  Other pages were already fine.  This probably wasn't noticed if no one used the account update page.
=> Fix using DeviceFingerPrinting properties on the server-side

.github/workflows/dotnetcore.yml, src/ApplicationCore/ApplicationCore.csproj, src/Infrastructure/Data/CatalogContext.cs, src/Infrastructure/Infrastructure.csproj, src/README.md, src/Web/Startup.cs, src/Web/Web.csproj
There will be a subsequent PR to swap up JSON.NET with the newer System.Text.Json library.
=> Upgrade app to .NET Core 3.1 and libraries to .NET Standard 2.1

.github/CODEOWNERS
More info @ https://help.github.com/en/github/creating-cloning-and-archiving-repositories/about-code-owners
=> Create CODEOWNERS for auto-reviewer assignment on PRs.

.github/workflows/dotnetcore.yml
Updating the samples build script to build on all PRs, not just PRs to master.
=> Build PRs regardless of target branch.

src/ApplicationCore/Entities/FraudProtectionApiModels/AccountProtection/Responses/ResultDetail.cs, src/ApplicationCore/Entities/FraudProtectionApiModels/Response/BaseAssessmentResponse.cs, src/ApplicationCore/Entities/FraudProtectionApiModels/RuleEvaluation.cs
Move RuleEvaluations out of AP as it will soon be in AP and PP. Rename RuleSetName in RuleEvaluations to Rule.
=> Some more api response updates

src/ApplicationCore/Entities/FraudProtectionApiModels/AccountProtection/Response/AccountProtectionDeviceAttributes.cs, src/ApplicationCore/Entities/FraudProtectionApiModels/AccountProtection/Response/Response.cs, src/ApplicationCore/Entities/FraudProtectionApiModels/AccountProtection/Response/ResponseError.cs, src/ApplicationCore/Entities/FraudProtectionApiModels/AccountProtection/Response/ResponseSuccess.cs, src/ApplicationCore/Entities/FraudProtectionApiModels/AccountProtection/Response/ResultDetail.cs, src/ApplicationCore/Entities/FraudProtectionApiModels/AccountProtection/Response/Score.cs, src/ApplicationCore/Entities/FraudProtectionApiModels/AccountProtection/Responses/ResponseSuccess.cs, src/ApplicationCore/Entities/FraudProtectionApiModels/Response/Enrichments.cs, src/ApplicationCore/Interfaces/IFraudPreventionService.cs, src/Infrastructure/Services/FraudProtectionService.cs, src/Web/Controllers/AccountController.cs, src/Web/Helpers/HelperFunctions.cs
These new attributes may optionally come back from the APIs, if it detects that a proxy might have been being used.  Also moved one file to a more accurate folder.
=> Add new Account Protection proxy attributes to Sign in and Sign up responses.

src/ApplicationCore/Entities/FraudProtectionApiModels/AccountProtection/Response/ResponseSuccess.cs, src/ApplicationCore/Entities/FraudProtectionApiModels/Response/BaseAssessmentResponse.cs
=> Update to include new Diagnostics section

docs/Account sign in (Account Protection) - Approved and rejected sign in flows.md, docs/Account sign up (Account Protection) - Approved and rejected sign up flows.md, docs/Account sign up (Purchase Protection) - Approved and rejected sign up flows.md, docs/Authenticate and call Fraud Protection.md, docs/Make a purchase - Approved purchase flow.md, docs/Make a purchase - Existing user.md, docs/Make a purchase - Guest user.md, docs/Make a purchase - Rejected purchase flow.md, docs/Record a chargeback.md, docs/Record a refund.md, docs/Send additional fraud signals using labels.md, src/Infrastructure/Extensions/Constants.cs, src/Infrastructure/Services/FraudProtectionService.cs
This PR starts passing the 'x-ms-dfpenvid' header on all Fraud Protection API calls.
=> Pass the environment ID header for API calls.

src/ApplicationCore/Entities/FraudProtectionApiModels/PurchaseStatus.cs, src/ApplicationCore/Entities/FraudProtectionApiModels/Response/Enrichments.cs, src/ApplicationCore/Entities/FraudProtectionApiModels/Response/PurchaseResponse.cs, src/ApplicationCore/Entities/OrderAggregate/OrderStatus.cs, src/Web/Controllers/BasketController.cs, src/Web/Helpers/HelperFunctions.cs, src/Web/ViewModels/Shared/CreditCardViewModel.cs, src/Web/Views/Basket/Checkout.cshtml, src/Web/Views/Basket/CheckoutDetails.cshtml, src/Web/Views/Manage/ManagePaymentInstrument.cshtml
- Add support for the Review merchant rule decision by sending only a bank auth and a purchase status... and no bank charge.  Both sent events have a status of "Unknown".
- Add additional device response attributes that have present for a little while and we're catching up with those new fields.
=> Support Review + Extra Device Response Attributes

src/Web/Controllers/AccountController.cs, src/Web/Views/Account/CustomAssessment.cshtml
=> Add support for generating guid's and timestamps in request payload

src/Web/ViewModels/CustomAssessmentViewModel.cs, src/Web/Views/Account/CustomAssessment.cshtml
Reflect that v1 custom assessments are deprecated, and v2 is preferred.
=> [Assessments] V2 for custom assessments is now the default.
